#spring:
#  profiles:
#    active: dev

server:
  port: 8081

  servlet:
    context-path: /api/product

spring:
  application:
    name: product-service

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.191:8848

#    sentinel:
#      eager: true
#      transport:
#        port: 8719
#        dashboard: 192.168.138.131:8858

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/foodie-shop?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:/mapper/*.xml

#feign:
#  sentinel:
#    enabled: true
#  hystrix:
#    enabled: false
#  client:
#    config:
#      default:
#        requestInterceptors:
#          - com.herring.feign.interceptor.TokenRelayRequestInterceptor
#        readTimeout: 60000
#        connectTimeout: 60000

#rocketmq:
#  name-server: 192.168.138.131:9876
#  producer:
#    group: product-group

#seata:
#  tx-service-group: herring_group
#
#  registry:
#    type: nacos
#    nacos:
#      application: seata-server
#      server-addr: 192.168.1.191:8848
##      group: SEATA_GROUP
#      username: nacos
#      password: nacos
#
#  config:
#    type: nacos
#    nacos:
#      server-addr: 192.168.1.191:8848
##      group: SEATA_GROUP
#      username: nacos
#      password: nacos